SRC = srcs/\
OBJECTS = objects/
INCLUDES = includes

run: compile
	clear
	@./a.out

run-v: compile-v
	./a.out

compile:
	@gcc -Wall -Werror -Wextra testing.c $(OBJECTS)ft*.o -Iincludes 

compile-v:
	gcc testing.c $(OBJECTS)ft*.o -Iincludes -Wall -Werror -Wextra

compile-fts:
	cd $(OBJECTS); gcc -c -I../$(INCLUDES) ../$(SRC)ft*.c ../$(SRC)extra/*.c
	@echo "Recompiled ft*.c's to ft*.o's"

re: compile-fts run
	

rev: compile-fts run-v

clean:
	rm $(OBJECTS)*.o